global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'mattermost-monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mattermost-server'
    static_configs:
      - targets: ['192.168.1.100:9100']
  
  - job_name: 'mattermost'
    static_configs:
      - targets: ['192.168.1.100:8067']

  - job_name: 'federate'
    scrape_interval: 5s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'

    static_configs:
      - targets:
        - '192.168.1.102:9090'